### ISSUE TITLE
Time-table action buttons UI on mobile screen

### ISSUE THREAD

**Issue by th3c0d3br34ker** [vatz88/FFCSonTheGo#148]
**Screenshots**
![image](https://user-images.githubusercontent.com/60807938/88764559-cb08bf80-d192-11ea-9dd4-4ec0bb852fe0.png)

**Smartphone (please complete the following information):**
 - Device: mobile phone

**Additional context**
Display the buttons vertically in mobile device.

**Comment by th3c0d3br34ker** [comment]
I can raise a PR if you want. 😄

**Comment by vatz88** [comment]
@th3c0d3br34ker thanks for taking interest and raising this issue.

There's scroll intensionally added. This design is responsive. I'm not sure stacking up buttons vertically helps because it'll take up additional vertical space, which may be a waste considering the small phone screen.

I'm still open to ideas if there's anything which can make the UI/UX better. May be share a screenshot of what you have in mind here.

Thanks!

**Comment by th3c0d3br34ker** [comment]
Yes, it does take up vertical space, but since it isn't between the search section or the timetable section (most used sections in this case), adding vertical space wont be a bad idea.

**Comment by vatz88** [comment]
But you still got some extra content to scroll before you could get to the time-table.

It's difficult to determine which UI/UX is correct because it very much depends on personal preference.
You're right but the current behaviour is not wrong either, so I guess we can skip this change for now.

Thanks!
