### ISSUE TITLE
Application Cache is removed, add Service Worker instead

### ISSUE THREAD

**Issue by vatz88** [vatz88/FFCSonTheGo#87]
Application Cache is removed as many users faced issues with not getting the updated site and also because it's a deprecated feature.

Add Service Worker to give offline support.

---

- [x] I have checked that no other similar issue is open or possible closed as `wontfix`

- [ ] Please assign me this issue, I would like to work on it.

**Comment by sangeeth96** [comment]
Was gonna make a PR about this but was busy preparing for two crappy exams. AppCache must die.

Could get this done quickly using WorkBox. Works like magic.

On 24-Jun-2018 00:44, Vatsal Joshi <notifications@github.com> wrote:

Application Cache is removed as many users faced issues with not getting the updated site and also because it's a deprecated feature.

Add Service Worker to give offline support.

________________________________

  *    I have checked that no other similar issue is open or possible closed as wontfix

  *    Please assign me this issue, I would like to work on it.

**Comment by vatz88** [comment]
@sangeeth96 If you want to take this up, assign it to yourself and remove the `available` label.

**Comment by vatz88** [comment]
@sangeeth96 do we really need WorkBox? We aren't doing any complex application. Just storing static files and serving them back when offline.

**Comment by sangeeth96** [comment]
Just saying it's prolly a one liner. Sure, I don't think it would be that much of a work anyway to add precaching and the likes. Plus, I was thinking we could also add notification when updated assets are available. WB makes things simpler but if the other route needs to be tried first, can be done. Anyway, I have exams tomorrow and day after so prolly can't do it before 25. If you're free, do try.

On 24-Jun-2018 00:57, Vatsal Joshi <notifications@github.com> wrote:

@sangeeth96<https://github.com/sangeeth96> do we really need WorkBox? We aren't doing any complex application. Just storing static files and serving them back when offline.

**Comment by vatz88** [comment]
Done #137 🥳
